#!/bin/bash
 
#This program creates a car and record the orders of a car rental bussiness 

plate=$1
model=$2
color=$3
pp=$4

#Create a car
if [ $# -ne 4 ]; then
echo " Incomplete input. Please enter Plate, Model, Colour and PP "
exit
fi

#If number of arguments is correct. Continue
plate=$1
model=$2
color=$3
pp=$4

#Adding new entry to the file maincarfile.txt
echo "$plate $model $color $pp" >> Database/maincarfile.txt
echo " " > Database/$plate.txt

bash frame.sh "Car Created sucessfully"

