#!/bin/bash

plate=$1
km=$2
dateout=$3
datein=$4

#Check if arguments are complete
if [ $# -ne 4 ]; then
echo " The arguments are not complete. Enter Plate, Km, Date-out and Date-in) "
exit 
fi

plate=$1
km=$2
dateout=$3
datein=$4

if [ ! -f "$plate.txt" ]; then
echo "This car was not created"
else 
echo "$km $dateout $datein" >> $plate.txt
fi

bash frame.sh "Trip info recorded succesfully" 


