#!bin/bash


#This script generates the summary of the car

bash frame.sh Summary

#Check if the user inputs any argument (check number of arguments) 
if [ $# -ne 1 ]; then
echo "No argument inputed.Run the program again and enter the name of the car"
exit
fi


#Check if file exists in database
FILE=$1
#Another option is moving to the database before checking the file
if [ ! -f "../Database/$FILE.txt" ]; then
 echo " Car not created. $FILE does not exist in the database "
 exit
fi

#Summary of the car 
total=0

While read line; 
do

#Show the sum of the km
for km in $line 
do 
  (( total=$total+$km ))
break
done

done < "$FILE.txt"

#Step 4: Show result nicely 
cd ../scripts/
bash frame.sh "Total distance travelled for $FILE was $total"
exit
